include ../include/msource/MakefileHome.in

HEADERS =  

all:  EVALSIM 

EVALSIM:  Evalsim.C $(HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@  Evalsim.C $(LDFLAGS) $(LIBS)

clean:
	rm -f *.o EVALSIM 





 
